apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: drupal
  name: drupal
spec:
  ports:
  - port: 30095
    protocol: TCP
    nodePort: 30095
  selector:
    app: drupal
  type: NodePort
status:
  loadBalancer: {}